POST http://localhost:8080/api/users/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NTNlZWVjNmIzNWMxYTVkYzJiNzZhYiIsImVtYWlsIjoia29rQHplcmlhLmNvbSIsImlhdCI6MTY4MzIyMjI5NSwiZXhwIjoxNjgzMjI1ODk1fQ.EDSUHDQWgXPqV-6LsHxCsOY1QBYTZUq8cUvZGJp6g1I


{
    "firstname": "Poumer",
    "lastname": "Outre",
    "email": "pmp@pok.dev",
    "phone": "2323252525",
    "password": "2222222222",
    "role": "admin"
}