POST http://localhost:8080/api/auth/login
Content-Type: application/json



# {
#     "email": "zmax@mpmp.com",
#     "password": "1234564"
# }

{
    "email": "max@ali.com",
    "password": "1234564"
}