POST http://localhost:8080/api/auth/register
Content-Type: application/json



{
    "firstname": "Matrix",
    "lastname": "Alex",
    "email": "max@ali.com",
    "phone": "2121212121",
    "password": "1234564"
}