POST http://localhost:8080/api/auth/register
Content-Type: application/json



{
    "firstname": "zakaria",
    "lastname": "koko",
    "email": "kok@zeria.com",
    "phone": "1212121212",
    "password": "111111"
}